// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "WiiUCore",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        .library(name: "WiiUCore", targets: ["WiiUCore"]),
    ],
    targets: [
        // Generated by `gomobile bind` from ios/mobile (see ios/scripts/build_mobile.sh).
        // iOS only, so the package declares iOS as its sole platform. Not checked
        // in; the build script must run before the package resolves.
        .binaryTarget(
            name: "Mobile",
            path: "Frameworks/Mobile.xcframework"
        ),
        .target(
            name: "WiiUCore",
            dependencies: ["Mobile"],
            path: "Sources/WiiUCore",
            resources: [
                .process("Resources"),
            ]
        ),
    ]
)
